"use strict";

/**
 * ═══════════════════════════════════════════════════════════════
 *  DATA KELUARGA — satu-satunya file yang perlu diedit untuk
 *  mengganti isi pohon keluarga. Lihat README.md untuk panduan.
 * ═══════════════════════════════════════════════════════════════
 *
 *  Aturan penting:
 *  • `id` harus unik dan tidak boleh diubah sembarangan (dipakai
 *    sebagai acuan di `parents` dan `spouses`).
 *  • `parents` berisi id ayah & ibu. Kosongkan ([]) untuk generasi
 *    paling atas atau untuk pasangan yang menikah masuk ke keluarga.
 *  • `spouses` cukup ditulis di SATU sisi saja (relasi otomatis
 *    dibuat dua arah).
 *  • Tulis anggota berdarah keluarga LEBIH DULU, baru pasangannya —
 *    ini menentukan sisi kiri/kanan pada kartu pasangan.
 *  • `photo` diisi path relatif, mis. "assets/photos/nama.jpg".
 *    Jika kosong atau file tidak ditemukan, avatar inisial otomatis
 *    dipakai sebagai gantinya.
 *  • Semua field selain `id`, `name`, dan `gender` bersifat opsional.
 */

const FAMILY_META = Object.freeze({
  familyName: "Keluarga Besar Wijaya",
  tagline: "Empat generasi, satu cerita — sejak 1938",
  footer: "Silsilah Keluarga Wijaya · dibuat dengan penuh sayang",
});

const FAMILY_DATA = Object.freeze([

  /* ═══ GENERASI I ═══════════════════════════════════════════ */
  {
    id: "g1-soekarno",
    name: "Soekarno Wijaya",
    nickname: "Opa Karno",
    gender: "M",
    photo: "",
    birthPlace: "Semarang",
    birthDate: "1938-03-17",
    deathDate: "2015-11-02",
    bloodType: "O",
    domicile: "Semarang, Jawa Tengah",
    occupation: "Pemilik Toko Kelontong",
    education: "Sekolah Rakyat",
    religion: "Katolik",
    parents: [],
    spouses: ["g1-sri"],
    quote: "Rezeki itu dibagi, bukan ditumpuk.",
    hobbies: ["Memancing", "Merawat burung perkutut", "Main catur"],
    favoriteFoods: ["Soto Semarang", "Tahu gimbal", "Kopi tubruk"],
    favoriteMusic: ["Keroncong", "Gesang"],
    traits: ["Sabar", "Suka bercerita", "Bangun jam 4 pagi"],
    funFacts: [
      "Membuka toko kelontong pertama keluarga pada tahun 1962 dengan modal hasil menjual sepeda.",
      "Tidak pernah absen mengantar cucu ke sekolah selama 8 tahun berturut-turut.",
      "Juara catur RT tiga tahun beruntun (1979–1981).",
    ],
  },
  {
    id: "g1-sri",
    name: "Sri Rahayu",
    nickname: "Oma Sri",
    gender: "F",
    photo: "",
    birthPlace: "Surakarta",
    birthDate: "1942-08-05",
    bloodType: "A",
    domicile: "Semarang, Jawa Tengah",
    occupation: "Ibu Rumah Tangga",
    education: "SMP",
    religion: "Katolik",
    parents: [],
    spouses: [],
    quote: "Masak itu bukan soal resep, tapi soal siapa yang mau kamu buat senang.",
    hobbies: ["Memasak", "Berkebun", "Menjahit"],
    favoriteFoods: ["Nasi liwet", "Serabi Solo", "Wedang jahe"],
    favoriteMusic: ["Langgam Jawa", "Waldjinah"],
    traits: ["Tegas tapi hangat", "Selalu masak berlebih", "Ingat semua ulang tahun"],
    funFacts: [
      "Resep opor buatannya jadi menu wajib Natal keluarga sampai sekarang.",
      "Menanam pohon mangga di halaman rumah tahun 1970 — masih berbuah tiap tahun.",
      "Bisa menyebutkan tanggal lahir seluruh 17 anggota keluarga tanpa melihat catatan.",
    ],
  },

  /* ═══ GENERASI II ══════════════════════════════════════════ */
  {
    id: "g2-bambang",
    name: "Bambang Wijaya",
    nickname: "Om Bambang",
    gender: "M",
    photo: "",
    birthPlace: "Semarang",
    birthDate: "1965-01-22",
    bloodType: "O",
    domicile: "Jakarta Selatan",
    occupation: "Insinyur Sipil",
    education: "S1 Teknik Sipil",
    religion: "Katolik",
    parents: ["g1-soekarno", "g1-sri"],
    spouses: ["g2-ratna"],
    quote: "Kalau fondasinya benar, sisanya tinggal sabar.",
    hobbies: ["Bersepeda", "Fotografi", "Otak-atik radio"],
    favoriteFoods: ["Sate kambing", "Gudeg", "Es teh manis"],
    favoriteMusic: ["Koes Plus", "The Beatles"],
    traits: ["Perfeksionis", "Datang selalu 15 menit lebih awal"],
    funFacts: [
      "Ikut membangun tiga jembatan di Jawa Tengah.",
      "Menyimpan lebih dari 4.000 foto keluarga hasil jepretannya sendiri.",
    ],
  },
  {
    id: "g2-ratna",
    name: "Ratna Dewi",
    nickname: "Tante Ratna",
    gender: "F",
    photo: "",
    birthPlace: "Bandung",
    birthDate: "1968-06-30",
    bloodType: "B",
    domicile: "Jakarta Selatan",
    occupation: "Guru SMA",
    education: "S1 Pendidikan Bahasa Inggris",
    religion: "Katolik",
    parents: [],
    spouses: [],
    quote: "Belajar itu seumur hidup, bukan sampai wisuda.",
    hobbies: ["Membaca novel", "Yoga", "Merangkai bunga"],
    favoriteFoods: ["Batagor", "Seblak", "Kopi susu"],
    favoriteMusic: ["Jazz", "Norah Jones"],
    traits: ["Pendengar yang baik", "Selalu bawa buku di tas"],
    funFacts: [
      "Mengajar Bahasa Inggris selama 28 tahun di sekolah yang sama.",
      "Pernah membawa tim debat sekolah juara tingkat provinsi.",
    ],
  },
  {
    id: "g2-sinta",
    name: "Sinta Wijaya",
    nickname: "Tante Sinta",
    gender: "F",
    photo: "",
    birthPlace: "Semarang",
    birthDate: "1968-09-14",
    bloodType: "A",
    domicile: "Surabaya, Jawa Timur",
    occupation: "Apoteker",
    education: "S1 Farmasi",
    religion: "Katolik",
    parents: ["g1-soekarno", "g1-sri"],
    spouses: ["g2-hendra"],
    quote: "Sehat itu murah, sakit yang mahal.",
    hobbies: ["Berkebun hidroponik", "Baking", "Jalan pagi"],
    favoriteFoods: ["Rujak cingur", "Rawon", "Es krim vanila"],
    favoriteMusic: ["Pop 90-an", "Sheila on 7"],
    traits: ["Rapi luar biasa", "Punya obat untuk segala keluhan"],
    funFacts: [
      "Membuka apotek keluarga pertama di Surabaya tahun 1998.",
      "Kue nastar buatannya selalu habis kurang dari dua jam saat Lebaran & Natal.",
    ],
  },
  {
    id: "g2-hendra",
    name: "Hendra Gunawan",
    nickname: "Om Hendra",
    gender: "M",
    photo: "",
    birthPlace: "Malang",
    birthDate: "1966-02-08",
    bloodType: "AB",
    domicile: "Surabaya, Jawa Timur",
    occupation: "Wiraswasta",
    education: "S1 Manajemen",
    religion: "Katolik",
    parents: [],
    spouses: [],
    quote: "Yang penting jalan dulu, sempurnanya belakangan.",
    hobbies: ["Badminton", "Kolektor jam tangan", "Nonton bola"],
    favoriteFoods: ["Bakso Malang", "Nasi goreng kambing"],
    favoriteMusic: ["Rock klasik", "Queen"],
    traits: ["Humoris", "Raja tawar-menawar"],
    funFacts: [
      "Punya koleksi 32 jam tangan, sebagian warisan dari ayahnya.",
      "Tidak pernah melewatkan final Piala Dunia sejak 1986.",
    ],
  },
  {
    id: "g2-agus",
    name: "Agus Wijaya",
    nickname: "Om Agus",
    gender: "M",
    photo: "",
    birthPlace: "Semarang",
    birthDate: "1972-12-03",
    bloodType: "O",
    domicile: "Denpasar, Bali",
    occupation: "Arsitek",
    education: "S2 Arsitektur",
    religion: "Katolik",
    parents: ["g1-soekarno", "g1-sri"],
    spouses: ["g2-maria"],
    quote: "Rumah yang baik itu yang bikin orang betah pulang.",
    hobbies: ["Melukis", "Surfing", "Kopi manual brew"],
    favoriteFoods: ["Ayam betutu", "Sate lilit", "Kopi V60"],
    favoriteMusic: ["Indie folk", "Payung Teduh"],
    traits: ["Santai", "Selalu bawa buku sketsa"],
    funFacts: [
      "Merancang lebih dari 40 vila di Bali.",
      "Pindah ke Bali tahun 2004 setelah liburan dua minggu yang tidak pernah berakhir.",
    ],
  },
  {
    id: "g2-maria",
    name: "Maria Tanuwijaya",
    nickname: "Tante Maria",
    gender: "F",
    photo: "",
    birthPlace: "Jakarta",
    birthDate: "1975-05-19",
    bloodType: "B",
    domicile: "Denpasar, Bali",
    occupation: "Desainer Interior",
    education: "S1 Desain Interior",
    religion: "Katolik",
    parents: [],
    spouses: [],
    quote: "Detail kecil yang bikin ruangan terasa hidup.",
    hobbies: ["Keramik", "Traveling", "Fotografi analog"],
    favoriteFoods: ["Nasi campur Bali", "Pasta carbonara"],
    favoriteMusic: ["Bossa nova", "Jazz kontemporer"],
    traits: ["Detail", "Selalu tahu warna cat yang tepat"],
    funFacts: [
      "Studio keramiknya di Ubud terbuka untuk keluarga setiap libur sekolah.",
      "Sudah mengunjungi 23 negara dan selalu membawa pulang satu piring keramik.",
    ],
  },

  /* ═══ GENERASI III ═════════════════════════════════════════ */
  {
    id: "g3-yosua",
    name: "Yosua Wijaya",
    nickname: "Yos",
    gender: "M",
    photo: "",
    birthPlace: "Jakarta",
    birthDate: "1995-07-11",
    bloodType: "O",
    domicile: "Jakarta Selatan",
    occupation: "Software Engineer",
    education: "S1 Teknik Informatika",
    religion: "Katolik",
    parents: ["g2-bambang", "g2-ratna"],
    spouses: ["g3-clara"],
    quote: "Kalau bisa diotomatisasi, kenapa dikerjakan manual?",
    hobbies: ["Ngoding", "Basket", "Board game"],
    favoriteFoods: ["Mie ayam", "Sushi", "Kopi susu gula aren"],
    favoriteMusic: ["Lo-fi", "Hindia"],
    traits: ["Suka riset sebelum beli apa pun", "Malam adalah waktu produktifnya"],
    funFacts: [
      "Membuat website silsilah keluarga ini.",
      "Menang hackathon kantor dua tahun berturut-turut.",
    ],
  },
  {
    id: "g3-clara",
    name: "Clara Santoso",
    nickname: "Clara",
    gender: "F",
    photo: "",
    birthPlace: "Yogyakarta",
    birthDate: "1996-11-28",
    bloodType: "A",
    domicile: "Jakarta Selatan",
    occupation: "Dokter Gigi",
    education: "Profesi Kedokteran Gigi",
    religion: "Katolik",
    parents: [],
    spouses: [],
    quote: "Senyum itu investasi paling murah.",
    hobbies: ["Pilates", "Merawat tanaman hias", "Baking"],
    favoriteFoods: ["Gudeg", "Croissant", "Matcha latte"],
    favoriteMusic: ["Taylor Swift", "Pop akustik"],
    traits: ["Ceria", "Punya 30+ tanaman di rumah"],
    funFacts: [
      "Bertemu Yosua saat sama-sama jadi panitia acara kampus.",
      "Punya kebun mini di balkon apartemen dengan 6 jenis herba.",
    ],
  },
  {
    id: "g3-nadia",
    name: "Nadia Wijaya",
    nickname: "Nad",
    gender: "F",
    photo: "",
    birthPlace: "Jakarta",
    birthDate: "1998-04-02",
    bloodType: "B",
    domicile: "Singapura",
    occupation: "Data Analyst",
    education: "S1 Statistika",
    religion: "Katolik",
    parents: ["g2-bambang", "g2-ratna"],
    spouses: [],
    quote: "Data nggak bohong, tapi sering disalahpahami.",
    hobbies: ["Lari", "Fotografi jalanan", "Belajar bahasa Jepang"],
    favoriteFoods: ["Chicken rice", "Ramen", "Es cendol"],
    favoriteMusic: ["City pop", "J-pop"],
    traits: ["Kompetitif", "Bangun subuh untuk lari"],
    funFacts: [
      "Sudah menyelesaikan tiga half-marathon.",
      "Bisa bicara empat bahasa: Indonesia, Inggris, Mandarin, Jepang.",
    ],
  },
  {
    id: "g3-kevin",
    name: "Kevin Gunawan",
    nickname: "Kevin",
    gender: "M",
    photo: "",
    birthPlace: "Surabaya",
    birthDate: "1994-10-09",
    bloodType: "AB",
    domicile: "Surabaya, Jawa Timur",
    occupation: "Apoteker",
    education: "S1 Farmasi",
    religion: "Katolik",
    parents: ["g2-sinta", "g2-hendra"],
    spouses: [],
    quote: "Meneruskan apotek itu bukan kewajiban, tapi pilihan yang saya syukuri.",
    hobbies: ["Badminton", "Memasak", "Main gitar"],
    favoriteFoods: ["Rawon", "Sate kelapa", "Es degan"],
    favoriteMusic: ["Rock alternatif", "Coldplay"],
    traits: ["Tenang", "Chef dadakan saat kumpul keluarga"],
    funFacts: [
      "Generasi kedua yang meneruskan apotek keluarga.",
      "Pemain gitar wajib di acara Natal keluarga.",
    ],
  },
  {
    id: "g3-michelle",
    name: "Michelle Gunawan",
    nickname: "Michy",
    gender: "F",
    photo: "",
    birthPlace: "Surabaya",
    birthDate: "1997-03-25",
    bloodType: "A",
    domicile: "Melbourne, Australia",
    occupation: "Pastry Chef",
    education: "Diploma Culinary Arts",
    religion: "Katolik",
    parents: ["g2-sinta", "g2-hendra"],
    spouses: [],
    quote: "Semua masalah terasa lebih ringan setelah bikin adonan.",
    hobbies: ["Baking", "Keramik", "Bersepeda"],
    favoriteFoods: ["Croissant", "Tiramisu", "Flat white"],
    favoriteMusic: ["Indie pop", "Lorde"],
    traits: ["Kreatif", "Bangun jam 3 pagi untuk kerja"],
    funFacts: [
      "Belajar baking pertama kali dari Oma Sri di dapur Semarang.",
      "Kue ulang tahun seluruh keluarga sekarang jadi tanggung jawabnya.",
    ],
  },
  {
    id: "g3-ryan",
    name: "Ryan Gunawan",
    nickname: "Ryan",
    gender: "M",
    photo: "",
    birthPlace: "Surabaya",
    birthDate: "2001-08-17",
    bloodType: "AB",
    domicile: "Bandung, Jawa Barat",
    occupation: "Mahasiswa Desain Grafis",
    education: "S1 Desain Komunikasi Visual (sedang berjalan)",
    religion: "Katolik",
    parents: ["g2-sinta", "g2-hendra"],
    spouses: [],
    quote: "Font yang salah bisa merusak segalanya.",
    hobbies: ["Ilustrasi digital", "Skateboard", "Kolektor sneaker"],
    favoriteFoods: ["Seblak", "Mie yamin", "Boba"],
    favoriteMusic: ["Hip-hop", "Rich Brian"],
    traits: ["Nokturnal", "Selalu pakai sneaker baru"],
    funFacts: [
      "Mendesain undangan reuni keluarga tahun lalu.",
      "Punya 40 ribu pengikut untuk karya ilustrasinya.",
    ],
  },
  {
    id: "g3-tiara",
    name: "Tiara Wijaya",
    nickname: "Tia",
    gender: "F",
    photo: "",
    birthPlace: "Denpasar",
    birthDate: "2003-01-30",
    bloodType: "O",
    domicile: "Denpasar, Bali",
    occupation: "Mahasiswa Arsitektur",
    education: "S1 Arsitektur (sedang berjalan)",
    religion: "Katolik",
    parents: ["g2-agus", "g2-maria"],
    spouses: [],
    quote: "Aku tumbuh di antara maket dan cat air.",
    hobbies: ["Melukis cat air", "Yoga", "Menyelam"],
    favoriteFoods: ["Sate lilit", "Smoothie bowl", "Es kelapa muda"],
    favoriteMusic: ["Indie folk", "Daniel Caesar"],
    traits: ["Perfeksionis diam-diam", "Sketsa di mana saja"],
    funFacts: [
      "Punya lisensi menyelam sejak umur 16.",
      "Karyanya pernah dipamerkan di galeri kecil di Ubud.",
    ],
  },
  {
    id: "g3-daniel",
    name: "Daniel Wijaya",
    nickname: "Dani",
    gender: "M",
    photo: "",
    birthPlace: "Denpasar",
    birthDate: "2006-06-21",
    bloodType: "O",
    domicile: "Denpasar, Bali",
    occupation: "Pelajar SMA",
    education: "SMA",
    religion: "Katolik",
    parents: ["g2-agus", "g2-maria"],
    spouses: [],
    quote: "Nanti aku mau keliling Indonesia naik motor.",
    hobbies: ["Surfing", "Gaming", "Basket"],
    favoriteFoods: ["Nasi campur Bali", "Burger", "Es teh"],
    favoriteMusic: ["EDM", "Pop"],
    traits: ["Enerjik", "Anggota termuda yang paling berisik"],
    funFacts: [
      "Belajar surfing dari ayahnya sejak umur 7 tahun.",
      "Anggota tim basket sekolah sebagai point guard.",
    ],
  },

  /* ═══ GENERASI IV ══════════════════════════════════════════ */
  {
    id: "g4-ethan",
    name: "Ethan Wijaya",
    nickname: "Ethan",
    gender: "M",
    photo: "",
    birthPlace: "Jakarta",
    birthDate: "2022-02-14",
    bloodType: "O",
    domicile: "Jakarta Selatan",
    occupation: "Balita",
    religion: "Katolik",
    parents: ["g3-yosua", "g3-clara"],
    spouses: [],
    quote: "Mobil! Mobil!",
    hobbies: ["Main mobil-mobilan", "Berenang"],
    favoriteFoods: ["Pisang", "Bubur ayam", "Yoghurt"],
    traits: ["Ramah ke semua orang", "Tidak bisa diam"],
    funFacts: [
      "Cicit pertama di keluarga Wijaya.",
      "Lahir tepat di Hari Valentine.",
    ],
  },
  {
    id: "g4-elena",
    name: "Elena Wijaya",
    nickname: "Ela",
    gender: "F",
    photo: "",
    birthPlace: "Jakarta",
    birthDate: "2024-09-08",
    bloodType: "A",
    domicile: "Jakarta Selatan",
    occupation: "Bayi",
    religion: "Katolik",
    parents: ["g3-yosua", "g3-clara"],
    spouses: [],
    hobbies: ["Tidur", "Ketawa"],
    favoriteFoods: ["ASI", "Puree wortel"],
    traits: ["Anteng", "Senyum ke siapa saja"],
    funFacts: [
      "Anggota keluarga termuda saat ini.",
      "Namanya diambil dari nama nenek buyut dari pihak ibu.",
    ],
  },
]);
