"use strict";

/**
 * Wilayah administratif Indonesia untuk pilihan Domisili.
 * Sumber: Kepmendagri No. 300.2.2-2138 Tahun 2025 (38 provinsi, 514 kabupaten/kota).
 *
 * Label sengaja dipendekkan: awalan "Kabupaten"/"Kota" dibuang agar ringkas.
 * Awalan "Kab." hanya dipertahankan pada 25 nama yang kalau dipolos
 * akan bentrok dengan kotanya (mis. Kab. Bandung vs Bandung di Jawa Barat).
 *
 * Dibangkitkan otomatis dari github.com/cahyadsn/wilayah — jangan diedit manual.
 */
const WILAYAH = Object.freeze({
  PROVINCES: Object.freeze([
    "Aceh",
    "Sumatera Utara",
    "Sumatera Barat",
    "Riau",
    "Jambi",
    "Sumatera Selatan",
    "Bengkulu",
    "Lampung",
    "Kepulauan Bangka Belitung",
    "Kepulauan Riau",
    "DKI Jakarta",
    "Jawa Barat",
    "Jawa Tengah",
    "DI Yogyakarta",
    "Jawa Timur",
    "Banten",
    "Bali",
    "Nusa Tenggara Barat",
    "Nusa Tenggara Timur",
    "Kalimantan Barat",
    "Kalimantan Tengah",
    "Kalimantan Selatan",
    "Kalimantan Timur",
    "Kalimantan Utara",
    "Sulawesi Utara",
    "Sulawesi Tengah",
    "Sulawesi Selatan",
    "Sulawesi Tenggara",
    "Gorontalo",
    "Sulawesi Barat",
    "Maluku",
    "Maluku Utara",
    "Papua",
    "Papua Barat",
    "Papua Selatan",
    "Papua Tengah",
    "Papua Pegunungan",
    "Papua Barat Daya",
  ]),

  // Format "<kab/kota>, <provinsi>", urut sesuai kode wilayah resmi.
  CITIES: Object.freeze([
    "Aceh Selatan, Aceh",
    "Aceh Tenggara, Aceh",
    "Aceh Timur, Aceh",
    "Aceh Tengah, Aceh",
    "Aceh Barat, Aceh",
    "Aceh Besar, Aceh",
    "Pidie, Aceh",
    "Aceh Utara, Aceh",
    "Simeulue, Aceh",
    "Aceh Singkil, Aceh",
    "Bireuen, Aceh",
    "Aceh Barat Daya, Aceh",
    "Gayo Lues, Aceh",
    "Aceh Jaya, Aceh",
    "Nagan Raya, Aceh",
    "Aceh Tamiang, Aceh",
    "Bener Meriah, Aceh",
    "Pidie Jaya, Aceh",
    "Banda Aceh, Aceh",
    "Sabang, Aceh",
    "Lhokseumawe, Aceh",
    "Langsa, Aceh",
    "Subulussalam, Aceh",
    "Tapanuli Tengah, Sumatera Utara",
    "Tapanuli Utara, Sumatera Utara",
    "Tapanuli Selatan, Sumatera Utara",
    "Nias, Sumatera Utara",
    "Langkat, Sumatera Utara",
    "Karo, Sumatera Utara",
    "Deli Serdang, Sumatera Utara",
    "Simalungun, Sumatera Utara",
    "Asahan, Sumatera Utara",
    "Labuhanbatu, Sumatera Utara",
    "Dairi, Sumatera Utara",
    "Toba, Sumatera Utara",
    "Mandailing Natal, Sumatera Utara",
    "Nias Selatan, Sumatera Utara",
    "Pakpak Bharat, Sumatera Utara",
    "Humbang Hasundutan, Sumatera Utara",
    "Samosir, Sumatera Utara",
    "Serdang Bedagai, Sumatera Utara",
    "Batu Bara, Sumatera Utara",
    "Padang Lawas Utara, Sumatera Utara",
    "Padang Lawas, Sumatera Utara",
    "Labuhanbatu Selatan, Sumatera Utara",
    "Labuhanbatu Utara, Sumatera Utara",
    "Nias Utara, Sumatera Utara",
    "Nias Barat, Sumatera Utara",
    "Medan, Sumatera Utara",
    "Pematangsiantar, Sumatera Utara",
    "Sibolga, Sumatera Utara",
    "Tanjungbalai, Sumatera Utara",
    "Binjai, Sumatera Utara",
    "Tebing Tinggi, Sumatera Utara",
    "Padangsidimpuan, Sumatera Utara",
    "Gunungsitoli, Sumatera Utara",
    "Pesisir Selatan, Sumatera Barat",
    "Kab. Solok, Sumatera Barat",
    "Sijunjung, Sumatera Barat",
    "Tanah Datar, Sumatera Barat",
    "Padang Pariaman, Sumatera Barat",
    "Agam, Sumatera Barat",
    "Lima Puluh Kota, Sumatera Barat",
    "Pasaman, Sumatera Barat",
    "Kepulauan Mentawai, Sumatera Barat",
    "Dharmasraya, Sumatera Barat",
    "Solok Selatan, Sumatera Barat",
    "Pasaman Barat, Sumatera Barat",
    "Padang, Sumatera Barat",
    "Solok, Sumatera Barat",
    "Sawahlunto, Sumatera Barat",
    "Padang Panjang, Sumatera Barat",
    "Bukittinggi, Sumatera Barat",
    "Payakumbuh, Sumatera Barat",
    "Pariaman, Sumatera Barat",
    "Kampar, Riau",
    "Indragiri Hulu, Riau",
    "Bengkalis, Riau",
    "Indragiri Hilir, Riau",
    "Pelalawan, Riau",
    "Rokan Hulu, Riau",
    "Rokan Hilir, Riau",
    "Siak, Riau",
    "Kuantan Singingi, Riau",
    "Kepulauan Meranti, Riau",
    "Pekanbaru, Riau",
    "Dumai, Riau",
    "Kerinci, Jambi",
    "Merangin, Jambi",
    "Sarolangun, Jambi",
    "Batanghari, Jambi",
    "Muaro Jambi, Jambi",
    "Tanjung Jabung Barat, Jambi",
    "Tanjung Jabung Timur, Jambi",
    "Bungo, Jambi",
    "Tebo, Jambi",
    "Jambi, Jambi",
    "Sungai Penuh, Jambi",
    "Ogan Komering Ulu, Sumatera Selatan",
    "Ogan Komering Ilir, Sumatera Selatan",
    "Muara Enim, Sumatera Selatan",
    "Lahat, Sumatera Selatan",
    "Musi Rawas, Sumatera Selatan",
    "Musi Banyuasin, Sumatera Selatan",
    "Banyuasin, Sumatera Selatan",
    "Ogan Komering Ulu Timur, Sumatera Selatan",
    "Ogan Komering Ulu Selatan, Sumatera Selatan",
    "Ogan Ilir, Sumatera Selatan",
    "Empat Lawang, Sumatera Selatan",
    "Penukal Abab Lematang Ilir, Sumatera Selatan",
    "Musi Rawas Utara, Sumatera Selatan",
    "Palembang, Sumatera Selatan",
    "Pagar Alam, Sumatera Selatan",
    "Lubuk Linggau, Sumatera Selatan",
    "Prabumulih, Sumatera Selatan",
    "Bengkulu Selatan, Bengkulu",
    "Rejang Lebong, Bengkulu",
    "Bengkulu Utara, Bengkulu",
    "Kaur, Bengkulu",
    "Seluma, Bengkulu",
    "Mukomuko, Bengkulu",
    "Lebong, Bengkulu",
    "Kepahiang, Bengkulu",
    "Bengkulu Tengah, Bengkulu",
    "Bengkulu, Bengkulu",
    "Lampung Selatan, Lampung",
    "Lampung Tengah, Lampung",
    "Lampung Utara, Lampung",
    "Lampung Barat, Lampung",
    "Tulang Bawang, Lampung",
    "Tanggamus, Lampung",
    "Lampung Timur, Lampung",
    "Way Kanan, Lampung",
    "Pesawaran, Lampung",
    "Pringsewu, Lampung",
    "Mesuji, Lampung",
    "Tulang Bawang Barat, Lampung",
    "Pesisir Barat, Lampung",
    "Bandar Lampung, Lampung",
    "Metro, Lampung",
    "Bangka, Kepulauan Bangka Belitung",
    "Belitung, Kepulauan Bangka Belitung",
    "Bangka Selatan, Kepulauan Bangka Belitung",
    "Bangka Tengah, Kepulauan Bangka Belitung",
    "Bangka Barat, Kepulauan Bangka Belitung",
    "Belitung Timur, Kepulauan Bangka Belitung",
    "Pangkal Pinang, Kepulauan Bangka Belitung",
    "Bintan, Kepulauan Riau",
    "Karimun, Kepulauan Riau",
    "Natuna, Kepulauan Riau",
    "Lingga, Kepulauan Riau",
    "Kepulauan Anambas, Kepulauan Riau",
    "Batam, Kepulauan Riau",
    "Tanjung Pinang, Kepulauan Riau",
    "Kepulauan Seribu, DKI Jakarta",
    "Jakarta Pusat, DKI Jakarta",
    "Jakarta Utara, DKI Jakarta",
    "Jakarta Barat, DKI Jakarta",
    "Jakarta Selatan, DKI Jakarta",
    "Jakarta Timur, DKI Jakarta",
    "Kab. Bogor, Jawa Barat",
    "Kab. Sukabumi, Jawa Barat",
    "Cianjur, Jawa Barat",
    "Kab. Bandung, Jawa Barat",
    "Garut, Jawa Barat",
    "Kab. Tasikmalaya, Jawa Barat",
    "Ciamis, Jawa Barat",
    "Kuningan, Jawa Barat",
    "Kab. Cirebon, Jawa Barat",
    "Majalengka, Jawa Barat",
    "Sumedang, Jawa Barat",
    "Indramayu, Jawa Barat",
    "Subang, Jawa Barat",
    "Purwakarta, Jawa Barat",
    "Karawang, Jawa Barat",
    "Kab. Bekasi, Jawa Barat",
    "Bandung Barat, Jawa Barat",
    "Pangandaran, Jawa Barat",
    "Bogor, Jawa Barat",
    "Sukabumi, Jawa Barat",
    "Bandung, Jawa Barat",
    "Cirebon, Jawa Barat",
    "Bekasi, Jawa Barat",
    "Depok, Jawa Barat",
    "Cimahi, Jawa Barat",
    "Tasikmalaya, Jawa Barat",
    "Banjar, Jawa Barat",
    "Cilacap, Jawa Tengah",
    "Banyumas, Jawa Tengah",
    "Purbalingga, Jawa Tengah",
    "Banjarnegara, Jawa Tengah",
    "Kebumen, Jawa Tengah",
    "Purworejo, Jawa Tengah",
    "Wonosobo, Jawa Tengah",
    "Kab. Magelang, Jawa Tengah",
    "Boyolali, Jawa Tengah",
    "Klaten, Jawa Tengah",
    "Sukoharjo, Jawa Tengah",
    "Wonogiri, Jawa Tengah",
    "Karanganyar, Jawa Tengah",
    "Sragen, Jawa Tengah",
    "Grobogan, Jawa Tengah",
    "Blora, Jawa Tengah",
    "Rembang, Jawa Tengah",
    "Pati, Jawa Tengah",
    "Kudus, Jawa Tengah",
    "Jepara, Jawa Tengah",
    "Demak, Jawa Tengah",
    "Kab. Semarang, Jawa Tengah",
    "Temanggung, Jawa Tengah",
    "Kendal, Jawa Tengah",
    "Batang, Jawa Tengah",
    "Kab. Pekalongan, Jawa Tengah",
    "Pemalang, Jawa Tengah",
    "Kab. Tegal, Jawa Tengah",
    "Brebes, Jawa Tengah",
    "Magelang, Jawa Tengah",
    "Surakarta, Jawa Tengah",
    "Salatiga, Jawa Tengah",
    "Semarang, Jawa Tengah",
    "Pekalongan, Jawa Tengah",
    "Tegal, Jawa Tengah",
    "Kulon Progo, DI Yogyakarta",
    "Bantul, DI Yogyakarta",
    "Gunungkidul, DI Yogyakarta",
    "Sleman, DI Yogyakarta",
    "Yogyakarta, DI Yogyakarta",
    "Pacitan, Jawa Timur",
    "Ponorogo, Jawa Timur",
    "Trenggalek, Jawa Timur",
    "Tulungagung, Jawa Timur",
    "Kab. Blitar, Jawa Timur",
    "Kab. Kediri, Jawa Timur",
    "Kab. Malang, Jawa Timur",
    "Lumajang, Jawa Timur",
    "Jember, Jawa Timur",
    "Banyuwangi, Jawa Timur",
    "Bondowoso, Jawa Timur",
    "Situbondo, Jawa Timur",
    "Kab. Probolinggo, Jawa Timur",
    "Kab. Pasuruan, Jawa Timur",
    "Sidoarjo, Jawa Timur",
    "Kab. Mojokerto, Jawa Timur",
    "Jombang, Jawa Timur",
    "Nganjuk, Jawa Timur",
    "Kab. Madiun, Jawa Timur",
    "Magetan, Jawa Timur",
    "Ngawi, Jawa Timur",
    "Bojonegoro, Jawa Timur",
    "Tuban, Jawa Timur",
    "Lamongan, Jawa Timur",
    "Gresik, Jawa Timur",
    "Bangkalan, Jawa Timur",
    "Sampang, Jawa Timur",
    "Pamekasan, Jawa Timur",
    "Sumenep, Jawa Timur",
    "Kediri, Jawa Timur",
    "Blitar, Jawa Timur",
    "Malang, Jawa Timur",
    "Probolinggo, Jawa Timur",
    "Pasuruan, Jawa Timur",
    "Mojokerto, Jawa Timur",
    "Madiun, Jawa Timur",
    "Surabaya, Jawa Timur",
    "Batu, Jawa Timur",
    "Pandeglang, Banten",
    "Lebak, Banten",
    "Kab. Tangerang, Banten",
    "Kab. Serang, Banten",
    "Tangerang, Banten",
    "Cilegon, Banten",
    "Serang, Banten",
    "Tangerang Selatan, Banten",
    "Jembrana, Bali",
    "Tabanan, Bali",
    "Badung, Bali",
    "Gianyar, Bali",
    "Klungkung, Bali",
    "Bangli, Bali",
    "Karangasem, Bali",
    "Buleleng, Bali",
    "Denpasar, Bali",
    "Lombok Barat, Nusa Tenggara Barat",
    "Lombok Tengah, Nusa Tenggara Barat",
    "Lombok Timur, Nusa Tenggara Barat",
    "Sumbawa, Nusa Tenggara Barat",
    "Dompu, Nusa Tenggara Barat",
    "Kab. Bima, Nusa Tenggara Barat",
    "Sumbawa Barat, Nusa Tenggara Barat",
    "Lombok Utara, Nusa Tenggara Barat",
    "Mataram, Nusa Tenggara Barat",
    "Bima, Nusa Tenggara Barat",
    "Kab. Kupang, Nusa Tenggara Timur",
    "Timor Tengah Selatan, Nusa Tenggara Timur",
    "Timor Tengah Utara, Nusa Tenggara Timur",
    "Belu, Nusa Tenggara Timur",
    "Alor, Nusa Tenggara Timur",
    "Flores Timur, Nusa Tenggara Timur",
    "Sikka, Nusa Tenggara Timur",
    "Ende, Nusa Tenggara Timur",
    "Ngada, Nusa Tenggara Timur",
    "Manggarai, Nusa Tenggara Timur",
    "Sumba Timur, Nusa Tenggara Timur",
    "Sumba Barat, Nusa Tenggara Timur",
    "Lembata, Nusa Tenggara Timur",
    "Rote Ndao, Nusa Tenggara Timur",
    "Manggarai Barat, Nusa Tenggara Timur",
    "Nagekeo, Nusa Tenggara Timur",
    "Sumba Tengah, Nusa Tenggara Timur",
    "Sumba Barat Daya, Nusa Tenggara Timur",
    "Manggarai Timur, Nusa Tenggara Timur",
    "Sabu Raijua, Nusa Tenggara Timur",
    "Malaka, Nusa Tenggara Timur",
    "Kupang, Nusa Tenggara Timur",
    "Sambas, Kalimantan Barat",
    "Mempawah, Kalimantan Barat",
    "Sanggau, Kalimantan Barat",
    "Ketapang, Kalimantan Barat",
    "Sintang, Kalimantan Barat",
    "Kapuas Hulu, Kalimantan Barat",
    "Bengkayang, Kalimantan Barat",
    "Landak, Kalimantan Barat",
    "Sekadau, Kalimantan Barat",
    "Melawi, Kalimantan Barat",
    "Kayong Utara, Kalimantan Barat",
    "Kubu Raya, Kalimantan Barat",
    "Pontianak, Kalimantan Barat",
    "Singkawang, Kalimantan Barat",
    "Kotawaringin Barat, Kalimantan Tengah",
    "Kotawaringin Timur, Kalimantan Tengah",
    "Kapuas, Kalimantan Tengah",
    "Barito Selatan, Kalimantan Tengah",
    "Barito Utara, Kalimantan Tengah",
    "Katingan, Kalimantan Tengah",
    "Seruyan, Kalimantan Tengah",
    "Sukamara, Kalimantan Tengah",
    "Lamandau, Kalimantan Tengah",
    "Gunung Mas, Kalimantan Tengah",
    "Pulang Pisau, Kalimantan Tengah",
    "Murung Raya, Kalimantan Tengah",
    "Barito Timur, Kalimantan Tengah",
    "Palangkaraya, Kalimantan Tengah",
    "Tanah Laut, Kalimantan Selatan",
    "Kotabaru, Kalimantan Selatan",
    "Banjar, Kalimantan Selatan",
    "Barito Kuala, Kalimantan Selatan",
    "Tapin, Kalimantan Selatan",
    "Hulu Sungai Selatan, Kalimantan Selatan",
    "Hulu Sungai Tengah, Kalimantan Selatan",
    "Hulu Sungai Utara, Kalimantan Selatan",
    "Tabalong, Kalimantan Selatan",
    "Tanah Bumbu, Kalimantan Selatan",
    "Balangan, Kalimantan Selatan",
    "Banjarmasin, Kalimantan Selatan",
    "Banjarbaru, Kalimantan Selatan",
    "Paser, Kalimantan Timur",
    "Kutai Kartanegara, Kalimantan Timur",
    "Berau, Kalimantan Timur",
    "Kutai Barat, Kalimantan Timur",
    "Kutai Timur, Kalimantan Timur",
    "Penajam Paser Utara, Kalimantan Timur",
    "Mahakam Ulu, Kalimantan Timur",
    "Balikpapan, Kalimantan Timur",
    "Samarinda, Kalimantan Timur",
    "Bontang, Kalimantan Timur",
    "Bulungan, Kalimantan Utara",
    "Malinau, Kalimantan Utara",
    "Nunukan, Kalimantan Utara",
    "Tana Tidung, Kalimantan Utara",
    "Tarakan, Kalimantan Utara",
    "Bolaang Mongondow, Sulawesi Utara",
    "Minahasa, Sulawesi Utara",
    "Kepulauan Sangihe, Sulawesi Utara",
    "Kepulauan Talaud, Sulawesi Utara",
    "Minahasa Selatan, Sulawesi Utara",
    "Minahasa Utara, Sulawesi Utara",
    "Minahasa Tenggara, Sulawesi Utara",
    "Bolaang Mongondow Utara, Sulawesi Utara",
    "Kep. Siau Tagulandang Biaro, Sulawesi Utara",
    "Bolaang Mongondow Timur, Sulawesi Utara",
    "Bolaang Mongondow Selatan, Sulawesi Utara",
    "Manado, Sulawesi Utara",
    "Bitung, Sulawesi Utara",
    "Tomohon, Sulawesi Utara",
    "Kotamobagu, Sulawesi Utara",
    "Banggai, Sulawesi Tengah",
    "Poso, Sulawesi Tengah",
    "Donggala, Sulawesi Tengah",
    "Toli-Toli, Sulawesi Tengah",
    "Buol, Sulawesi Tengah",
    "Morowali, Sulawesi Tengah",
    "Banggai Kepulauan, Sulawesi Tengah",
    "Parigi Moutong, Sulawesi Tengah",
    "Tojo Una Una, Sulawesi Tengah",
    "Sigi, Sulawesi Tengah",
    "Banggai Laut, Sulawesi Tengah",
    "Morowali Utara, Sulawesi Tengah",
    "Palu, Sulawesi Tengah",
    "Kepulauan Selayar, Sulawesi Selatan",
    "Bulukumba, Sulawesi Selatan",
    "Bantaeng, Sulawesi Selatan",
    "Jeneponto, Sulawesi Selatan",
    "Takalar, Sulawesi Selatan",
    "Gowa, Sulawesi Selatan",
    "Sinjai, Sulawesi Selatan",
    "Bone, Sulawesi Selatan",
    "Maros, Sulawesi Selatan",
    "Pangkajene dan Kepulauan, Sulawesi Selatan",
    "Barru, Sulawesi Selatan",
    "Soppeng, Sulawesi Selatan",
    "Wajo, Sulawesi Selatan",
    "Sidenreng Rappang, Sulawesi Selatan",
    "Pinrang, Sulawesi Selatan",
    "Enrekang, Sulawesi Selatan",
    "Luwu, Sulawesi Selatan",
    "Tana Toraja, Sulawesi Selatan",
    "Luwu Utara, Sulawesi Selatan",
    "Luwu Timur, Sulawesi Selatan",
    "Toraja Utara, Sulawesi Selatan",
    "Makassar, Sulawesi Selatan",
    "Parepare, Sulawesi Selatan",
    "Palopo, Sulawesi Selatan",
    "Kolaka, Sulawesi Tenggara",
    "Konawe, Sulawesi Tenggara",
    "Muna, Sulawesi Tenggara",
    "Buton, Sulawesi Tenggara",
    "Konawe Selatan, Sulawesi Tenggara",
    "Bombana, Sulawesi Tenggara",
    "Wakatobi, Sulawesi Tenggara",
    "Kolaka Utara, Sulawesi Tenggara",
    "Konawe Utara, Sulawesi Tenggara",
    "Buton Utara, Sulawesi Tenggara",
    "Kolaka Timur, Sulawesi Tenggara",
    "Konawe Kepulauan, Sulawesi Tenggara",
    "Muna Barat, Sulawesi Tenggara",
    "Buton Tengah, Sulawesi Tenggara",
    "Buton Selatan, Sulawesi Tenggara",
    "Kendari, Sulawesi Tenggara",
    "Bau Bau, Sulawesi Tenggara",
    "Kab. Gorontalo, Gorontalo",
    "Boalemo, Gorontalo",
    "Bone Bolango, Gorontalo",
    "Pohuwato, Gorontalo",
    "Gorontalo Utara, Gorontalo",
    "Gorontalo, Gorontalo",
    "Pasangkayu, Sulawesi Barat",
    "Mamuju, Sulawesi Barat",
    "Mamasa, Sulawesi Barat",
    "Polewali Mandar, Sulawesi Barat",
    "Majene, Sulawesi Barat",
    "Mamuju Tengah, Sulawesi Barat",
    "Maluku Tengah, Maluku",
    "Maluku Tenggara, Maluku",
    "Kepulauan Tanimbar, Maluku",
    "Buru, Maluku",
    "Seram Bagian Timur, Maluku",
    "Seram Bagian Barat, Maluku",
    "Kepulauan Aru, Maluku",
    "Maluku Barat Daya, Maluku",
    "Buru Selatan, Maluku",
    "Ambon, Maluku",
    "Tual, Maluku",
    "Halmahera Barat, Maluku Utara",
    "Halmahera Tengah, Maluku Utara",
    "Halmahera Utara, Maluku Utara",
    "Halmahera Selatan, Maluku Utara",
    "Kepulauan Sula, Maluku Utara",
    "Halmahera Timur, Maluku Utara",
    "Pulau Morotai, Maluku Utara",
    "Pulau Taliabu, Maluku Utara",
    "Ternate, Maluku Utara",
    "Tidore Kepulauan, Maluku Utara",
    "Kab. Jayapura, Papua",
    "Kepulauan Yapen, Papua",
    "Biak Numfor, Papua",
    "Sarmi, Papua",
    "Keerom, Papua",
    "Waropen, Papua",
    "Supiori, Papua",
    "Mamberamo Raya, Papua",
    "Jayapura, Papua",
    "Manokwari, Papua Barat",
    "Fak Fak, Papua Barat",
    "Teluk Bintuni, Papua Barat",
    "Teluk Wondama, Papua Barat",
    "Kaimana, Papua Barat",
    "Manokwari Selatan, Papua Barat",
    "Pegunungan Arfak, Papua Barat",
    "Merauke, Papua Selatan",
    "Boven Digoel, Papua Selatan",
    "Mappi, Papua Selatan",
    "Asmat, Papua Selatan",
    "Nabire, Papua Tengah",
    "Puncak Jaya, Papua Tengah",
    "Paniai, Papua Tengah",
    "Mimika, Papua Tengah",
    "Puncak, Papua Tengah",
    "Dogiyai, Papua Tengah",
    "Intan Jaya, Papua Tengah",
    "Deiyai, Papua Tengah",
    "Jayawijaya, Papua Pegunungan",
    "Pegunungan Bintang, Papua Pegunungan",
    "Yahukimo, Papua Pegunungan",
    "Tolikara, Papua Pegunungan",
    "Mamberamo Tengah, Papua Pegunungan",
    "Yalimo, Papua Pegunungan",
    "Lanny Jaya, Papua Pegunungan",
    "Nduga, Papua Pegunungan",
    "Kab. Sorong, Papua Barat Daya",
    "Sorong Selatan, Papua Barat Daya",
    "Raja Ampat, Papua Barat Daya",
    "Tambrauw, Papua Barat Daya",
    "Maybrat, Papua Barat Daya",
    "Sorong, Papua Barat Daya",
  ]),
});
